name: admin_panel_app
description: Admin/Store Panel for Grocery Loyalty System with Arabic RTL support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  # Firebase
  firebase_core: ^4.2.0
  firebase_app_check: ^0.4.1+1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  cloud_functions: ^6.0.3
  firebase_messaging: ^16.0.3

  # Routing
  go_router: ^16.2.5

  # Localization
  intl: 0.20.2

  # UI Components
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  fl_chart: ^1.1.1
  shimmer: ^3.0.0

  # Utilities
  uuid: ^4.2.2
  path: ^1.8.3
  mime: ^2.0.0
  timeago: ^3.6.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.4.7
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts (Cairo for Arabic support)
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
        - asset: fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: fonts/Cairo-Medium.ttf
          weight: 500
        - asset: fonts/Cairo-Light.ttf
          weight: 300

